### ISSUE TITLE
Zoom state interferes with rendering of the ColorSelection "Tolerance" label

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#111]
If you zoom in before using the ColorSelection tool, the tolerance label text becomes distorted. I also don't think the selected pixels should be anti-aliased.

![image](https://user-images.githubusercontent.com/26802537/112176312-5f1a1200-8bce-11eb-9820-e6d1e6963a67.png)

zooming further...

![image](https://user-images.githubusercontent.com/26802537/112176327-62ad9900-8bce-11eb-9727-75e05f319d16.png)

**Comment by alicelucas** [comment]
@DavidStirling This seems to have been fixed so I'll close it -- but let me know if not.
