### ISSUE TITLE
Pen tool is weird

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#112]
Drawing with the pen tool gives very strange results, it almost seems to be doing superpixels or something?

Particularly when zoomed in it's difficult to draw a simple line, in the show below I drew towards the bottom left, but look at the edges..

![image](https://user-images.githubusercontent.com/26802537/112177198-1b73d800-8bcf-11eb-8a17-dfdcd425f5e2.png)

Thickness adjustment would also be nice.

It seems to particularly struggle when drawing diagonally:
![image](https://user-images.githubusercontent.com/26802537/112177524-642b9100-8bcf-11eb-877a-60ff51951975.png)

**Comment by alicelucas** [comment]
Agreed! 
This is also related to issue #103  and issue #105 .
