### ISSUE TITLE
Feature request: "Undo" button

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#114]
I think this would help a fair bit in the future, it's easy to accidentally mess up or delete an annotation.

**Comment by 0x00b1** [comment]
Yep. I agree.

@alicelucas This will be tricky for non-Redux operations (e.g. our tool actions). We should come up with a plan to address this ASAP even if we don't plan on implementing it ASAP so we don't accidentally shoot ourselves in the foot (a lovely American idiom eh).

**Comment by alicelucas** [comment]
@0x00b1 Yes, I'd love to have a conversation about this! Definitely seems non-trivial to me.
