### ISSUE TITLE
Polygon selections should be more greedy

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#115]
If a partial pixel is selected by a path, the region should probably include it (maybe if a substantial fraction was within the box?). When selecting small objects with RectangularSelection, for example, the drawn box (blue) contains almost-whole pixels around the edge which are missed by the dotted selection box.

![image](https://user-images.githubusercontent.com/26802537/112179111-c5a02f80-8bd0-11eb-869b-352c40e6476c.png)

**Comment by DavidStirling** [comment]
As a guess, I'm thinking that in converting the box coordinate floats to a path we're calling `math.floor`, whereas we probably want to use `math.round`

**Comment by alicelucas** [comment]
@DavidStirling Yep, there are definitely inconsistencies like that in the code. We're finally witnessing some of that. We need to consistency use `Math.floor` OR `Math.round`.

**Comment by 0x00b1** [comment]
@alicelucas We both knew our sloppiness around this would come back to bite us!

**Comment by alicelucas** [comment]
This has been fixed, but we should still watch out for any inconsistent roundings in our current tools.
