### ISSUE TITLE
New/Add/Subtract buttons should select when their labels are clicked

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#116]
It's confusing at the moment because clicking the labels triggers a selection animation, yet doesn't toggle the tool mode. I'd thought that this meant the options were disabled, but actually you just have to click on the radio button itself. We should either disable the label animation or make the label trigger the button too.

**Comment by alicelucas** [comment]
(@0x00b1 Correct me if I'm wrong) @DavidStirling I think that what we'll do is disable the animation that you see when clicking on these buttons. That way it'll will be clear to the user that they have to actually click on the radio button. 
Thanks for bringing this up!

**Comment by DavidStirling** [comment]
Something to keep in mind is that category selection is done by clicking the labels, so you might favour allowing this selection mode for consistency.

**Comment by pearlryder** [comment]
I raised the same issue w/ the Zoom in buttons, because that was my first instinct for where to click. There's inconsistency w/in the app at the moment as David raised with category labels and I pointed out for "Center image automatically" (both activate when selecting the label).
