### ISSUE TITLE
Toggling display of 'unknown' category hides all annotations

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#118]
The show/hide button on the label marker of the unknown category currently toggles display of all annotations, not just those in the unknown category. Other category toggles seem to work fine. I suspect that the wrong selector is being used.

**Comment by DavidStirling** [comment]
This might be intermittent, or already got fixed. It seems to have started working again.

**Comment by alicelucas** [comment]
@DavidStirling Yes, seems like it works now! Closing this but I'll keep a close eye on it.
