### ISSUE TITLE
QuickSelection gets confused when it touches the image border

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#119]
It seems that if the QuickSelection tool runs up against the border, the resulting annotation is inverted.

![image](https://user-images.githubusercontent.com/26802537/112202257-8b8e5800-8be7-11eb-9bfd-a42c2b102ba2.png)

![image](https://user-images.githubusercontent.com/26802537/112202302-9b0da100-8be7-11eb-9f8a-02d064957e76.png)

![image](https://user-images.githubusercontent.com/26802537/112202361-aeb90780-8be7-11eb-9d2e-da78ec6d5074.png)

**Comment by alicelucas** [comment]
It seems like it's only `contour` that is affected and not the `mask`. I have noticed something similar in other tools. We'll have to look at the algorithm we use to compute the contour from a polygon.
