### ISSUE TITLE
Clicking with the pointer should cycle between multiple overlapping annotations.

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#123]
Currently, if one annotation is hidden behind another, it becomes impossible to select the one underneath using the pointer tool - meaning you'd need to delete the annotation covering it to modify the smaller object. I'd suggest that clicking the same annotation multiple times should look for additional annotations underneath the target pixel.

**Comment by alicelucas** [comment]
`node.intersects(point)` might be what we need here

**Comment by alicelucas** [comment]
Closing because functionality is there. There is a small bug, but I'll add it as a separate issue.
