### ISSUE TITLE
Open image/Example dialogue box shows non-English language  

### ISSUE THREAD

**Issue by NasimJ** [piximi/image-viewer#124]
Open image-->Example dialogue box is currently showing a non-English language (even though the language setting is set for English).
<img width="602" alt="DialogueBox" src="https://user-images.githubusercontent.com/55710463/112215253-897fc580-8bf6-11eb-8578-cebaa90d6a13.png">
<img width="449" alt="LanguageSetting" src="https://user-images.githubusercontent.com/55710463/112215271-900e3d00-8bf6-11eb-86a9-810ec9f571c5.png">

Also, the dialogue box doesn't have the option to close (i.e: if one changes their mind and want to close the box), and clicking outside the dialogue box doesn't close it.

**Comment by pearlryder** [comment]
I've closed this issue but opened a new one for @NasimJ's second point (there should be a way to get back out of the dialog box if you don't want to open an example).
