### ISSUE TITLE
Create a category by enter

### ISSUE THREAD

**Issue by NasimJ** [piximi/image-viewer#132]
It would be handy when Creating a new category if the **CREATE** button would work with enter (instead of clicking by mouse), this way it would be faster and less switching between keyboard and mouse.
<img width="448" alt="CreateCategory" src="https://user-images.githubusercontent.com/55710463/112218170-cc8f6800-8bf9-11eb-8257-0301479c61f8.png">

**Comment by NasimJ** [comment]
Maybe to add to this, it would be very helpful to be able to create a category right after selection. 
i.e: I think right after selecting an area, having the option (R-click for example) to create a new category or add to an existing one would be very handy.
<img width="209" alt="CreateCategory2" src="https://user-images.githubusercontent.com/55710463/112219158-03b24900-8bfb-11eb-9227-d799133577fb.png">
(in the selected box above if I could R-click and create a category right there would be faster)

**Comment by alicelucas** [comment]
Writing down the current idea that we have in mind: on mouse up, show a little pop up with the available categories and allow the user to select one of them. The user will also have a "New category" as one of the options.
