### ISSUE TITLE
Zooming broken with greyscale images

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#133]
Not sure if it's because my image is large or greyscale, but the zoom tool sends the image flying all over the page. I'm seeing scrollbars for the main app too.

![image](https://user-images.githubusercontent.com/26802537/112218227-df09a180-8bf9-11eb-8d57-0802294d2c72.png)

**Comment by alicelucas** [comment]
@DavidStirling Would you mind sending us this image?

**Comment by alicelucas** [comment]
@DavidStirling I believe one of our earlier commits should have fixed this. Now it works on my end (with the image you send). I am closing for now, but do let me know if it didn't change on your end.

**Comment by alicelucas** [comment]
The image should be centered, too, now. Again do let me know if not the case!
