### ISSUE TITLE
Zooming in with rectangular select does not zoom to the right region 

### ISSUE THREAD

**Issue by alicelucas** [piximi/image-viewer#136]

**Comment by alicelucas** [comment]
This is what is happening: a `onClick` event is happening right after the `onMouseUp` event. We need to prevent the `onClick` to happen when `OnMouseUp` has happened already.

**Comment by pearlryder** [comment]
Example of this breaking and selecting way, way more zoomed than I wanted: 

Uploading Screen Recording 2021-03-24 at 4.43.27 PM.mov…
