### ISSUE TITLE
Zoom tool buttons should change zoom modes

### ISSUE THREAD

**Issue by pearlryder** [piximi/image-viewer#138]
I'd like to be able to change zoom modes by clicking over top of the text -- this was my intuitive place to try to click when using the browser. At the moment, you have to click on the radio button in order to change modes.

Center image automatically does work to select by clicking on the text or within the small box. 

https://user-images.githubusercontent.com/28375904/112375526-c52f9380-8cb9-11eb-8135-45694c57f5e6.mov

**Comment by alicelucas** [comment]
Looks like this was fixed, by someone! I'll close it.
