### ISSUE TITLE
Load the Quick Annotation tool model on application start and on a separate thread

### ISSUE THREAD

**Issue by NasimJ** [piximi/image-viewer#139]
When selected a pen annotation tool and defined a category, then selecting quick annotation tool, Piximi froze and the two tools are both show as selected. 
<img width="989" alt="ToolSelection" src="https://user-images.githubusercontent.com/55710463/112376701-273cc880-8cbb-11eb-9694-50de71f16a18.png">

**Comment by alicelucas** [comment]
This is a problem with the QuickAnnotation tool itself which takes a bit of time to load. I am changing the title to reflect this!

**Comment by alicelucas** [comment]
Also referencing this issue: https://github.com/piximi/image-viewer/issues/94

**Comment by alicelucas** [comment]
Oops, turns out we already has an issue about that (https://github.com/piximi/image-viewer/issues/71). Closing.
