### ISSUE TITLE
Add possibility of sampling image channels and modifying brightness, contrast, and opacity for each

### ISSUE THREAD

**Issue by alicelucas** [piximi/image-viewer#222]
We will eventually have a conversation about this with @0x00b1 and the rest of the engineering team, but I am writing this meta-issue here so that it stays in our radar. Some of the things we'll have to think about:
- Where this channel dialog will be placed in our app
- How to modify the brightness, contrast or opacity for each channel. I think our current intention is to use Konva's filters.

**Comment by 0x00b1** [comment]
I worked on this a bit. @diskontinuum worked on this too.

A few ideas to motivate the conversation:

- Color adjustments (e.g. brightness and vibrancy) are performed by opening the `Color adjustment` tool and making changes in the options drawer.
- `ColorAdjustmentOptions` includes a `List` of channels. Users can perform color adjustments to one or more of the channels.
- The aforementioned channels `List` is limited to three channels (i.e. `Red`, `Green`, and `Blue`). If a user has an image that uses a color space wider than `RGB` then they must manually associate their channels.

**Comment by DavidStirling** [comment]
Would we be passing the adjusted image data into the tools, or sampling the original source data? If we do the former that might give us an easy path towards operating on specific channels across all tools, rather than doing individual implementations.
