### ISSUE TITLE
Contours or no contours

### ISSUE THREAD

**Issue by alicelucas** [piximi/image-viewer#234]
Our annotations instances currently use two properties, `contour` and `mask`. Relying on the contours, in some cases, has introduced bugs in our code and may slow down the performance. 

Today we ask the question: do we really need those contours? Can we keep all the functionality we currently have by using the `mask` information only, while not getting any decrease in peformance?

_Where have `contours` caused problems?_
Computing contours from masks (which is done by the Object, Color, and Quick selection tools) may sometime not provide accurate results and ultimately shows a shape that is different than the one selected by the user.  The PenSelection tool is a perfect example of this.
Furthermore, we use the `isoLines()` algorithm, which can be quite slow in some cases: loading a lot of exported annotations with isolines results in a very long importing time. Another example is the use of pen selection on the Malaria image, where the resulting annotation takes a while to show -- this is again due to the time needed for `Isoline` to compute the contours.

_Where are `annotation.contours` used?_
- They are used to define a `Konva.Line` shape and show a selected or confirmed annotation. Note that we could use `annotation.mask` instead by rendering a `Konva.Image`.
- They are used to resize the transformer boxes (and the contours that are inside the box). The resize simply scales and offsets the contour by the transformation determined by the user. This is probably feasible with a mask, but I am not sure it will be as performant. 
- The bounding box of our annotations are computed from the contours we extract.  That being said, it should be possible to compute these from the `mask`. 

@0x00b1 and @DavidStirling what are your thoughts? Feel free to add anything that is missing here.

**Comment by DavidStirling** [comment]
I'm wondering whether there might be a more efficient way to generate lines from mask boundaries. What format are the annotation points imported in? Might there be a way to avoid needing to run isolines again after each import?

**Comment by alicelucas** [comment]
@DavidStirling when we export the annotations, we actually currently don't export the `contours`, only the mask. I guess we could export the contours as well? That would solve the problem of very slow imports of annotation files.

**Comment by DavidStirling** [comment]
If we can avoid exporting contours then perhaps we should, it's not really necessary and you're still having to calculate them in the first place. I think the mask-only approach sounds like a good solution if you can get Konva to resize masks nicely.
