### ISSUE TITLE
Add possibility of exporting annotations as label matrices

### ISSUE THREAD

**Issue by alicelucas** [piximi/image-viewer#258]

**Comment by DavidStirling** [comment]
Was looking at this, but we need to decide something.

Ideally we'd want one label ID per object, but that raises the issue of how to handle different categories. I see two options:

1 - Have an individual label image for each category, with objects numbered 1->x on each, which means multiple output images.
2 - Have a single label image with categories numbered 1->x, which sacrifices the ability to seperate touching objects.
