### ISSUE TITLE
Fix keyboard shortcuts 

### ISSUE THREAD

**Issue by alicelucas** [piximi/image-viewer#266]

**Comment by alicelucas** [comment]
@DavidStirling I would need your help for coming up with the right shortcuts for each tool. 

For some of the tools, it's pretty easy:
- "h" for hand
- "z" for zoom
- "i" for intensity adjustment (is that good?)
- "r" for rectangular annotation
- "e" for elliptical annotation
- "l" for lasso
- "m" for magnetic annotation
- "c" for color annotation
- "q" for quick annotation

Questions: 
- What do we do for Pointer tool, Pen Annotation Tool, and Polygonal Annotation tool? They all start with the same letter.

- What shortcut do we want to use to switch between pan and zoom?

- For special selection modes, we currently have "Shift" for add and maybe (it might have to be implemented) "Alt/Option" for Subtract. We still need shortcut for intersection. 



A note: we should bring back tooltips with the name of the tool when hovered over the tool.  Not the whole tooltip card that took a lot of place like before, but just a small tooltip so that the user knows what they are clicking on.

**Comment by DavidStirling** [comment]
Those sound fine. I don't think that every tool needs a dedicated shortcut, so maybe we shouldn't worry too much.

I'd consider renaming Pointer to "Select" with 'S' as the shortcut. Pen could be 'D' for 'Draw'.

Regarding pan/zoom, I'd still be in favour of merging these into a single tool with different modes.

Wouldn't worry about the intersection mode, it's not going to be extensively used.

Agreed on the tooltips.
