### ISSUE TITLE
Batch or merge multiple dispatch calls.

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#284]
I believe this is going to be an important performance optimisation. Currently we have a lot of functions which generate multiple `dispatch` events, each of which triggers rendering. There are a few techniques we can use to ensure that rendering only occurs once during those multi-update sequences. I'll look into it.

**Comment by alicelucas** [comment]
Oh, exciting! Let me know how it goes.

**Comment by 0x00b1** [comment]
@DavidStirling fwiw `batch` has been great
