### ISSUE TITLE
Permit overlapping objects while keeping the functionality on clicking on existing annotation

### ISSUE THREAD

**Issue by alicelucas** [piximi/image-viewer#30]
Suppose we have an instance on our image. Clicking on it currently results in the onMouseDown() event of the selected operator to be called. (as opposed to show show the transformer around it).

This is why when clicking on an instance in Lasso or Polygonal mode, we involuntarily enter the drawing mode. (It actually happens if we are in the Rectangular/Ellipse tools, but we don't see it because we click and release immediately instead of dragging to see the shape being drawn.)

@0x00b1 When the user clicks on the Stage, should we be checking whether the clicked (x, y) coordinates belong to one of the bounding boxes of our existing annotations? If yes, we should do an early return before entering the operator's onMouseDown?

**Comment by 0x00b1** [comment]
@alicelucas If I understand your question correctly, no. We permit overlapping objects. We should take a look at other applications to see they method for dealing with this.

**Comment by alicelucas** [comment]
Great! I changed the title of the issue to be more accurate.

**Comment by alicelucas** [comment]
Will get resolved once we implement add/subtract/intersect options.
