### ISSUE TITLE
Add a name and one or two sentence description to the tool options drawer

### ISSUE THREAD

**Issue by 0x00b1** [piximi/image-viewer#62]
![image](https://user-images.githubusercontent.com/315821/111516453-4cb15b80-872a-11eb-8ee2-7d4a6d9624a3.png)

**Comment by 0x00b1** [comment]
We had this and I removed it for some stupid reason.

**Comment by alicelucas** [comment]
I had assigned myself to this but then realized that it might be best to double check with @0x00b1 on what we want to write.

**Comment by alicelucas** [comment]
Made it a bit more clear for now by changing wording: we now refer to a "selected" annotation instead of an "existing" annotation to make it clearer that the annotation should be selected first.

**Comment by alicelucas** [comment]
I have taken a first pass at this, but it would be best if multiple people look over these.
