### ISSUE TITLE
Improve magnetic edge detection for smaller features

### ISSUE THREAD

**Issue by pearlryder** [piximi/image-viewer#78]
Use case: I'm trying to annotate the nuclei in the default image in Piximi. I wanted to use the magnetic tool to snap to the nuclear border, but it was very "blocky" -- it seemed to be snapping to big chunks. Perhaps this is related to trying to improve performance by modifying the network map of pixels? 

![Screen Shot 2021-03-17 at 2 37 19 PM](https://user-images.githubusercontent.com/28375904/111520229-47eea680-872e-11eb-84c8-2c878f9184b8.png)

**Comment by 0x00b1** [comment]
Confirmed! 

This is related to the downsampling we do to make the performance cheaper. We should rethink this and consider a different trade-off.
