### ISSUE TITLE
Add a pop up to show color annotation threshold value

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#80]
Currently colourselection only shows the outline to be selected once mouse is released. Considering that how far you drag before releasing dictates how much tolerance is given, this isn't really useful.

I previously had written code to display the current tolerance in a popup while dragging, is that still around? Drawing the detection as you drag also shouldn't be too hard, if it can't be done efficiently with the outline then perhaps make use of the overlay layer I had it making before?

**Comment by DavidStirling** [comment]
Correction - preview does work, but tolerance should still be shown to let the use know what's happening.

**Comment by 0x00b1** [comment]
@DavidStirling I agree!
