### ISSUE TITLE
Lasso still reverts to a polygon tool after a second click/mouse release.

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#81]
The code to stop it instantly terminating if you don't hold down the mouse is working, but if you click again (or drag some way then release) the tool drops an anchor and reverts to selecting straight lines for a polygon. It should continue doing lasso after each anchor, because nobody wants to have to hold down the mouse for their entire drawing.

**Comment by alicelucas** [comment]
This would be an easy fix, but waiting for confirmation by @0x00b1 after more research has been done.

**Comment by 0x00b1** [comment]
grumble grumble fine
