### ISSUE TITLE
Allow deletion of objects, or make it more intuitive

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#83]
I expected the delete key to work, but it didn't. It's also not clear how to 'select' an object once it's added. Do I need to use the hand tool? Because if so it isn't working.

**Comment by alicelucas** [comment]
@DavidStirling If you first right click an object and then press escape or backspace on your keyboard, does the annotation get removed?

**Comment by DavidStirling** [comment]
@alicelucas Yes, though I would have expected 'Escape' to deselect rather than deleting.

I think this is currently confusing because right clicks pop up a normal context menu when not clicking on an object, so it's not obvious to the user that they should expect functionality from this button. If you're going to use right click binds then any click on the canvas should be intercepted.

**Comment by alicelucas** [comment]
Thanks again @DavidStirling  for your feedback! Super helpful.

Whenever you find the time (https://piximi.github.io/image-viewer/) -- could you try again pressing on Escape (and also on Backspace) to delete an annotation. Currently the user should be able to delete in two different situations, if you could try both of these:

- Right after on mouse up, when user has not confirmed the annotation with Enter yet. The user can delete it with Escape or Backspace. 
-  After selecting a confirmed annotation (the annotation was previously confirmed with Enter), the user can delete it with Escape or Backspace. 

If that still does not work for you, then I'm wondering if perhaps it could be something that has to do with the key names that a Windows keyboard might be using.

Note that @0x00b1 is currently implementing a "pointer tool" to select the annotations, so hopefully the Right-click problems soon won't be a problem anymore.

**Comment by DavidStirling** [comment]
Seems to be working perfectly, well done!

**Comment by alicelucas** [comment]
Awesome, thank you! We're good to close this issue.
