### ISSUE TITLE
Tools in 'New' mode should reset when a new drag operation is made.

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#85]
Currently, once you've drawn but not finalised a region (resizer box shows), there seems to be no good way to get rid of/cancel it. If anything the whole tool breaks.

The workflow I'd like is that if I draw a rectangle, starting to draw elsewhere on the canvas will erase that incomplete object and start again.

**Comment by alicelucas** [comment]
I'll note here that this is mentioned as well in issue #87.
