### ISSUE TITLE
Hitting 'Enter' on an incomplete lasso/polygon should close the loop

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#86]
If I'm zoomed out a lot it can be tricky to precisely hit the starting anchor to finish drawing, particularly with a touchpad. If the user presses 'enter' I'd like it to just add a final, straight line connecting the current cursor position to the starting anchor.

**Comment by 0x00b1** [comment]
Good idea.

**Comment by alicelucas** [comment]
Thanks for the suggestion @DavidStirling ! It's been implemented and is a great new feature.
