### ISSUE TITLE
On add, subtract and intersection tools

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#87]
I don't think the current setup is overly intuitive. It's not obvious that you need to finalize an object with 'enter' and re-select it before drawing again. I expected switching tool mode and drawing again to edit a non-finalized selection (since I logically don't want to finish my partially drawn segmentation when in 'add' mode).

I'd suggest that you add a bit of overlay shading to a selected (but not finalised) region, to make it clear what's going to be selected on 'enter'. If drawing begins in 'add' or 'subtract' mode, persist the original region, then re-draw the outline/shading with the new section. If drawing begins in 'new' mode, scrap the previous drawing.

**Comment by alicelucas** [comment]
@DavidStirling thanks for suggesting this! It's been implemented -- except for the overlay shading. It's a great suggestion, but we'll implement that in the future as we are currently focusing on getting the right functionalities working.
