### ISSUE TITLE
Update object annotation model weights

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#88]
With cells I'm getting results like this. If it's because the midpoint is treated as where to find the object, that needs to be obvious in the UI. Maybe add a crosshair to the middle of the box?

![objectselection](https://user-images.githubusercontent.com/26802537/111530394-9bb2bd00-8739-11eb-8284-3db94309085f.png)

**Comment by 0x00b1** [comment]
Confirmed! We need to update the model weights.
