### ISSUE TITLE
If a tool has a loading time, let the user know

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#93]
Having to wait for tools isn't the end of the world, but currently you don't know it's still loading until you've clicked, at which point things freeze and the resulting selection from a partial drawing is useless. Some kind of "preparing tool" indicator would help a lot until these are properly optimised.

**Comment by 0x00b1** [comment]
I agree but we don't plan on having loading times for any of the tools! The two that take a moment to load (quick annotation and object annotation) are slow because of other bugs!
